version: "3.8"
services:
  neverstop_app:
    container_name: neverstop_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - neverstop_db
    networks:
      - app_network

  neverstop_nginx:
    container_name: neverstop_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - neverstop_app
    environment:
      NGINX_FPM_HOST: neverstop_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  neverstop_db:
    container_name: neverstop_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: neverstop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdminNeverStop
    links:
      - neverstop_db:db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - app_network

  neverstop_redis:
    container_name: neverstop_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

  
networks:
  app_network:
    driver: bridge

